package Interface;

import java.awt.Color;

public class DBAdminUI extends javax.swing.JFrame {

    Color DefaultColor,ClickedColor,HoverColor;
    public DBAdminUI() {
        initComponents();
        DefaultColor=new Color(240,240,240);
        ClickedColor=new Color(0,204,204);
        HoverColor=new Color(204,255,255);
        
        //Set default color to pan on run time
        AHome.setBackground(DefaultColor);
        AAssignEmp.setBackground(DefaultColor);
        AOrderfromSuppliers.setBackground(DefaultColor);
        AGenerateReport.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AAssignEmp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AGenerateReport = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AOrderfromSuppliers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AHome = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JPanel();
        StatusBar = new javax.swing.JPanel();
        MusicMartTxt = new javax.swing.JLabel();
        MenuName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(153, 153, 153));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setPreferredSize(new java.awt.Dimension(171, 100));
        Logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\LOGO\\Logos\\LOGO_DashBoard.png")); // NOI18N
        Logo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 0, -1, 89));

        Menu.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        AAssignEmp.setPreferredSize(new java.awt.Dimension(240, 48));
        AAssignEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AAssignEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AAssignEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AAssignEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AAssignEmpMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\PROJECT\\MusicMart_RunTimeTerror\\src\\main\\java\\Icons\\briefcase-search (1).png")); // NOI18N
        jLabel2.setText("Assign Employees to Jobs");

        javax.swing.GroupLayout AAssignEmpLayout = new javax.swing.GroupLayout(AAssignEmp);
        AAssignEmp.setLayout(AAssignEmpLayout);
        AAssignEmpLayout.setHorizontalGroup(
            AAssignEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AAssignEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        AAssignEmpLayout.setVerticalGroup(
            AAssignEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AAssignEmpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Menu.add(AAssignEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 201, 240, 50));

        AGenerateReport.setPreferredSize(new java.awt.Dimension(240, 48));
        AGenerateReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AGenerateReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AGenerateReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AGenerateReportMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AGenerateReportMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\PROJECT\\MusicMart_RunTimeTerror\\src\\main\\java\\Icons\\chart-areaspline (1).png")); // NOI18N
        jLabel4.setText("Generate Report");

        javax.swing.GroupLayout AGenerateReportLayout = new javax.swing.GroupLayout(AGenerateReport);
        AGenerateReport.setLayout(AGenerateReportLayout);
        AGenerateReportLayout.setHorizontalGroup(
            AGenerateReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGenerateReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AGenerateReportLayout.setVerticalGroup(
            AGenerateReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        Menu.add(AGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 338, 240, 51));

        AOrderfromSuppliers.setPreferredSize(new java.awt.Dimension(240, 48));
        AOrderfromSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AOrderfromSuppliersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AOrderfromSuppliersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AOrderfromSuppliersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AOrderfromSuppliersMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\PROJECT\\MusicMart_RunTimeTerror\\src\\main\\java\\Icons\\forwardburger (1).png")); // NOI18N
        jLabel3.setText("Order from Suppliers");

        javax.swing.GroupLayout AOrderfromSuppliersLayout = new javax.swing.GroupLayout(AOrderfromSuppliers);
        AOrderfromSuppliers.setLayout(AOrderfromSuppliersLayout);
        AOrderfromSuppliersLayout.setHorizontalGroup(
            AOrderfromSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AOrderfromSuppliersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AOrderfromSuppliersLayout.setVerticalGroup(
            AOrderfromSuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Menu.add(AOrderfromSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 269, 240, 51));

        AHome.setPreferredSize(new java.awt.Dimension(240, 48));
        AHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AHomeMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\PROJECT\\MusicMart_RunTimeTerror\\src\\main\\java\\Icons\\home (1).png")); // NOI18N
        jLabel6.setText("Home");

        javax.swing.GroupLayout AHomeLayout = new javax.swing.GroupLayout(AHome);
        AHome.setLayout(AHomeLayout);
        AHomeLayout.setHorizontalGroup(
            AHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AHomeLayout.setVerticalGroup(
            AHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Menu.add(AHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 240, 50));

        jPanel5.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jDesktopPanel.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPanel.setPreferredSize(new java.awt.Dimension(660, 440));
        jDesktopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 660, 440));

        StatusBar.setBackground(new java.awt.Color(0, 204, 204));

        MusicMartTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MusicMartTxt.setForeground(new java.awt.Color(255, 255, 255));
        MusicMartTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MusicMartTxt.setText("Music Mart");

        MenuName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MenuName.setForeground(new java.awt.Color(255, 255, 255));
        MenuName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuName.setText("Admin");

        javax.swing.GroupLayout StatusBarLayout = new javax.swing.GroupLayout(StatusBar);
        StatusBar.setLayout(StatusBarLayout);
        StatusBarLayout.setHorizontalGroup(
            StatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusBarLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(StatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusBarLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(MusicMartTxt))
                    .addComponent(MenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        StatusBarLayout.setVerticalGroup(
            StatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusBarLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(MusicMartTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuName)
                .addGap(25, 25, 25))
        );

        jPanel5.add(StatusBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 660, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AHomeMousePressed
        // TODO add your handling code here:
        AHome.setBackground(ClickedColor);
        AAssignEmp.setBackground(DefaultColor);
        AOrderfromSuppliers.setBackground(DefaultColor);
        AGenerateReport.setBackground(DefaultColor);
        
        MenuName.setText("Admin Home");
    }//GEN-LAST:event_AHomeMousePressed

    private void AAssignEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AAssignEmpMousePressed
        // TODO add your handling code here:
        AHome.setBackground(DefaultColor);
        AAssignEmp.setBackground(ClickedColor);
        AOrderfromSuppliers.setBackground(DefaultColor);
        AGenerateReport.setBackground(DefaultColor);
        
        MenuName.setText("Assign Employees to Jobs");
    }//GEN-LAST:event_AAssignEmpMousePressed

    private void AOrderfromSuppliersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOrderfromSuppliersMousePressed
        // TODO add your handling code here:
        AHome.setBackground(DefaultColor);
        AAssignEmp.setBackground(DefaultColor);
        AOrderfromSuppliers.setBackground(ClickedColor);
        AGenerateReport.setBackground(DefaultColor);
        
        MenuName.setText("Order from Suppliers");
    }//GEN-LAST:event_AOrderfromSuppliersMousePressed

    private void AGenerateReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AGenerateReportMousePressed
        // TODO add your handling code here:
        AHome.setBackground(DefaultColor);
        AAssignEmp.setBackground(DefaultColor);
        AOrderfromSuppliers.setBackground(DefaultColor);
        AGenerateReport.setBackground(ClickedColor);
        
        MenuName.setText("Generate Report");
    }//GEN-LAST:event_AGenerateReportMousePressed

    private void AHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AHomeMouseEntered
        // TODO add your handling code here:
        AHome.setBackground(HoverColor);
    }//GEN-LAST:event_AHomeMouseEntered

    private void AAssignEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AAssignEmpMouseEntered
        // TODO add your handling code here:
        AAssignEmp.setBackground(HoverColor);
    }//GEN-LAST:event_AAssignEmpMouseEntered

    private void AOrderfromSuppliersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOrderfromSuppliersMouseEntered
        // TODO add your handling code here:
        AOrderfromSuppliers.setBackground(HoverColor);
    }//GEN-LAST:event_AOrderfromSuppliersMouseEntered

    private void AGenerateReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AGenerateReportMouseEntered
        // TODO add your handling code here:
        AGenerateReport.setBackground(HoverColor);
    }//GEN-LAST:event_AGenerateReportMouseEntered

    private void AHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AHomeMouseClicked
        // TODO add your handling code here:
        AdminHome ad1 = new AdminHome();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(ad1).setVisible(true);
    }//GEN-LAST:event_AHomeMouseClicked

    private void AAssignEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AAssignEmpMouseClicked
        // TODO add your handling code here:
        AssignEmptoJobs ad2 = new AssignEmptoJobs();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(ad2).setVisible(true);
    }//GEN-LAST:event_AAssignEmpMouseClicked

    private void AOrderfromSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOrderfromSuppliersMouseClicked
        // TODO add your handling code here:
        OrderfromSuppliers ad3 = new OrderfromSuppliers();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(ad3).setVisible(true);
    }//GEN-LAST:event_AOrderfromSuppliersMouseClicked

    private void AGenerateReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AGenerateReportMouseClicked
        // TODO add your handling code here:
        GenerateReport ad4 = new GenerateReport();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(ad4).setVisible(true);
    }//GEN-LAST:event_AGenerateReportMouseClicked

    private void AHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AHomeMouseExited
        // TODO add your handling code here:
        AHome.setBackground(DefaultColor);
    }//GEN-LAST:event_AHomeMouseExited

    private void AAssignEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AAssignEmpMouseExited
        // TODO add your handling code here:
        AAssignEmp.setBackground(DefaultColor);
    }//GEN-LAST:event_AAssignEmpMouseExited

    private void AOrderfromSuppliersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOrderfromSuppliersMouseExited
        // TODO add your handling code here:
        AOrderfromSuppliers.setBackground(DefaultColor);
    }//GEN-LAST:event_AOrderfromSuppliersMouseExited

    private void AGenerateReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AGenerateReportMouseExited
        // TODO add your handling code here:
        AGenerateReport.setBackground(DefaultColor);
    }//GEN-LAST:event_AGenerateReportMouseExited

    private void AHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AHomeMouseReleased

    }//GEN-LAST:event_AHomeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBAdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AAssignEmp;
    private javax.swing.JPanel AGenerateReport;
    private javax.swing.JPanel AHome;
    private javax.swing.JPanel AOrderfromSuppliers;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel MenuName;
    private javax.swing.JLabel MusicMartTxt;
    private javax.swing.JPanel StatusBar;
    private javax.swing.JPanel jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
