package Interface;

import java.awt.Color;

public class DBCustomerUI extends javax.swing.JFrame {

    Color DefaultColor,ClickedColor,HoverColor;
    public DBCustomerUI() {
        initComponents();
        DefaultColor=new Color(240,240,240);
        ClickedColor=new Color(0,204,204);
        HoverColor=new Color(204,255,255);
        
        //Set default color to pan on run time
        CHome.setBackground(DefaultColor);
        COrderIns.setBackground(DefaultColor);
        COrderAcc.setBackground(DefaultColor);
        CReqRepairJob.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        COrderIns = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        COrderAcc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CReqRepairJob = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CHome = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        StatusBar = new javax.swing.JPanel();
        MusicMartTxt = new javax.swing.JLabel();
        MenuName = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 540));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(210, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        COrderIns.setPreferredSize(new java.awt.Dimension(240, 48));
        COrderIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COrderInsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                COrderInsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                COrderInsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                COrderInsMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\PROJECT\\MusicMart_RunTimeTerror\\src\\main\\java\\Icons\\shopping-search (1).png")); // NOI18N
        jLabel2.setText("Order Instruments");

        javax.swing.GroupLayout COrderInsLayout = new javax.swing.GroupLayout(COrderIns);
        COrderIns.setLayout(COrderInsLayout);
        COrderInsLayout.setHorizontalGroup(
            COrderInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(COrderInsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        COrderInsLayout.setVerticalGroup(
            COrderInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(COrderIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 197, 240, -1));

        COrderAcc.setPreferredSize(new java.awt.Dimension(240, 48));
        COrderAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COrderAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                COrderAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                COrderAccMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                COrderAccMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\PROJECT\\MusicMart_RunTimeTerror\\src\\main\\java\\Icons\\feature-search (1).png")); // NOI18N
        jLabel3.setText("Order Accerssories");

        javax.swing.GroupLayout COrderAccLayout = new javax.swing.GroupLayout(COrderAcc);
        COrderAcc.setLayout(COrderAccLayout);
        COrderAccLayout.setHorizontalGroup(
            COrderAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(COrderAccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        COrderAccLayout.setVerticalGroup(
            COrderAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(COrderAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 263, 240, -1));

        CReqRepairJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CReqRepairJobMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CReqRepairJobMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CReqRepairJobMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CReqRepairJobMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\PROJECT\\MusicMart_RunTimeTerror\\src\\main\\java\\Icons\\message-arrow-right (1).png")); // NOI18N
        jLabel4.setText("Request Repair Job");

        javax.swing.GroupLayout CReqRepairJobLayout = new javax.swing.GroupLayout(CReqRepairJob);
        CReqRepairJob.setLayout(CReqRepairJobLayout);
        CReqRepairJobLayout.setHorizontalGroup(
            CReqRepairJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CReqRepairJobLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        CReqRepairJobLayout.setVerticalGroup(
            CReqRepairJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(CReqRepairJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 329, 240, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(171, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\LOGO\\Logos\\LOGO_DashBoard.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        CHome.setPreferredSize(new java.awt.Dimension(240, 48));
        CHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CHomeMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\PROJECT\\MusicMart_RunTimeTerror\\src\\main\\java\\Icons\\home (1).png")); // NOI18N
        jLabel6.setText("Home");

        javax.swing.GroupLayout CHomeLayout = new javax.swing.GroupLayout(CHome);
        CHome.setLayout(CHomeLayout);
        CHomeLayout.setHorizontalGroup(
            CHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CHomeLayout.setVerticalGroup(
            CHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(CHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 540));

        StatusBar.setBackground(new java.awt.Color(0, 204, 204));

        MusicMartTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MusicMartTxt.setForeground(new java.awt.Color(255, 255, 255));
        MusicMartTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MusicMartTxt.setText("Music Mart");

        MenuName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MenuName.setForeground(new java.awt.Color(255, 255, 255));
        MenuName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuName.setText("Customer");

        javax.swing.GroupLayout StatusBarLayout = new javax.swing.GroupLayout(StatusBar);
        StatusBar.setLayout(StatusBarLayout);
        StatusBarLayout.setHorizontalGroup(
            StatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusBarLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(StatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusBarLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(MusicMartTxt))
                    .addComponent(MenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        StatusBarLayout.setVerticalGroup(
            StatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusBarLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(MusicMartTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuName)
                .addGap(25, 25, 25))
        );

        jPanel1.add(StatusBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 660, -1));

        jDesktopPanel.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPanel.setPreferredSize(new java.awt.Dimension(660, 440));
        jDesktopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 660, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHomeMousePressed
        // TODO add your handling code here:
        CHome.setBackground(ClickedColor);
        COrderIns.setBackground(DefaultColor);
        COrderAcc.setBackground(DefaultColor);
        CReqRepairJob.setBackground(DefaultColor);
        
        MenuName.setText("Home");
    }//GEN-LAST:event_CHomeMousePressed

    private void COrderInsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COrderInsMousePressed
        // TODO add your handling code here:
        CHome.setBackground(DefaultColor);
        COrderIns.setBackground(ClickedColor);
        COrderAcc.setBackground(DefaultColor);
        CReqRepairJob.setBackground(DefaultColor);
        
        MenuName.setText("Order Instruments");
    }//GEN-LAST:event_COrderInsMousePressed

    private void COrderAccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COrderAccMousePressed
        // TODO add your handling code here:
        CHome.setBackground(DefaultColor);
        COrderIns.setBackground(DefaultColor);
        COrderAcc.setBackground(ClickedColor);
        CReqRepairJob.setBackground(DefaultColor);
        
        MenuName.setText("Order Accersories");
    }//GEN-LAST:event_COrderAccMousePressed

    private void CReqRepairJobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CReqRepairJobMousePressed
        // TODO add your handling code here:
        CHome.setBackground(DefaultColor);
        COrderIns.setBackground(DefaultColor);
        COrderAcc.setBackground(DefaultColor);
        CReqRepairJob.setBackground(ClickedColor);
        
        MenuName.setText("Request Repair Job");
    }//GEN-LAST:event_CReqRepairJobMousePressed

    private void CHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHomeMouseClicked
        // TODO add your handling code here:
        CustomerHome cu1 = new CustomerHome();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(cu1).setVisible(true);
    }//GEN-LAST:event_CHomeMouseClicked

    private void COrderInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COrderInsMouseClicked
        // TODO add your handling code here:
        OrderInstruments cu2 = new OrderInstruments();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(cu2).setVisible(true);
    }//GEN-LAST:event_COrderInsMouseClicked

    private void COrderAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COrderAccMouseClicked
        // TODO add your handling code here:
        OrderAccersories cu3 = new OrderAccersories();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(cu3).setVisible(true);
    }//GEN-LAST:event_COrderAccMouseClicked

    private void CReqRepairJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CReqRepairJobMouseClicked
        // TODO add your handling code here:
        RequestRepairJob cu4 = new RequestRepairJob();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(cu4).setVisible(true);
    }//GEN-LAST:event_CReqRepairJobMouseClicked

    private void CHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHomeMouseEntered
        // TODO add your handling code here:
        CHome.setBackground(HoverColor);
    }//GEN-LAST:event_CHomeMouseEntered

    private void COrderInsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COrderInsMouseEntered
        // TODO add your handling code here:
        COrderIns.setBackground(HoverColor);
    }//GEN-LAST:event_COrderInsMouseEntered

    private void COrderAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COrderAccMouseEntered
        // TODO add your handling code here:
        COrderAcc.setBackground(HoverColor);
    }//GEN-LAST:event_COrderAccMouseEntered

    private void CReqRepairJobMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CReqRepairJobMouseEntered
        // TODO add your handling code here:
        CReqRepairJob.setBackground(HoverColor);
    }//GEN-LAST:event_CReqRepairJobMouseEntered

    private void CHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHomeMouseExited
        // TODO add your handling code here:
        CHome.setBackground(DefaultColor);
    }//GEN-LAST:event_CHomeMouseExited

    private void COrderInsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COrderInsMouseExited
        // TODO add your handling code here:
        COrderIns.setBackground(DefaultColor);
    }//GEN-LAST:event_COrderInsMouseExited

    private void COrderAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COrderAccMouseExited
        // TODO add your handling code here:
        COrderAcc.setBackground(DefaultColor);
    }//GEN-LAST:event_COrderAccMouseExited

    private void CReqRepairJobMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CReqRepairJobMouseExited
        // TODO add your handling code here:
        CReqRepairJob.setBackground(DefaultColor);
    }//GEN-LAST:event_CReqRepairJobMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBCustomerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CHome;
    private javax.swing.JPanel COrderAcc;
    private javax.swing.JPanel COrderIns;
    private javax.swing.JPanel CReqRepairJob;
    private javax.swing.JLabel MenuName;
    private javax.swing.JLabel MusicMartTxt;
    private javax.swing.JPanel StatusBar;
    private javax.swing.JPanel jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
