/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Model.User;

public class UserUI extends javax.swing.JFrame {

    ArrayList<User> userDB;
    String sc;
    
    public UserUI() {
        initComponents();
        setLocationRelativeTo(null);
        userDB = new ArrayList<>();
        UserDetails();
    }   
    private void UserDetails ()
        {
        userDB.add(new User("admin","12345"));
        userDB.add(new User("customer", "0987"));
        }

    private boolean validate(User user) throws NullPointerException, NumberFormatException
        {
        for(User u : userDB)
        {
            if(u.getUsername().equals(user.getUsername())&&u.getpassword().equals(user.getpassword()))
            {
                return true;
            }
        }
        return false;
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsername = new javax.swing.JTextField();
        jpassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 300));
        getContentPane().setLayout(null);
        getContentPane().add(jUsername);
        jUsername.setBounds(250, 120, 300, 30);
        getContentPane().add(jpassword);
        jpassword.setBounds(250, 160, 300, 30);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 90, 100, 24);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 120, 80, 19);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 160, 80, 19);

        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 200, 70, 23);

        LOGO.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\LOGO\\Logos\\LOGO_wBackground.png")); // NOI18N
        getContentPane().add(LOGO);
        LOGO.setBounds(340, 10, 100, 80);

        BackGround.setIcon(new javax.swing.ImageIcon("D:\\Edu. STORE\\SLIIT\\UOB Year 1\\UOB Semester 2\\2- Object Oriented Programming-JAVA (OOP)\\Group Project\\Login_Image.jpg")); // NOI18N
        BackGround.setMaximumSize(new java.awt.Dimension(750, 300));
        BackGround.setMinimumSize(new java.awt.Dimension(750, 300));
        BackGround.setPreferredSize(new java.awt.Dimension(750, 300));
        getContentPane().add(BackGround);
        BackGround.setBounds(0, 0, 750, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
                String Username = jUsername.getText();
                String password = jpassword.getText();
                User temp = new User (Username, password);
                boolean result = validate(temp);
                if(result)
                {
                    DashboardUI da = new DashboardUI();
                    this.setVisible(false);
                    da.setVisible(true);
                    if (Username.equals("admin"))
                    {
                        da.ButtonA();
                    }
                    else if (Username.equals("customer"))
                    {
                        da.ButtonB();
                    }
                }
                else
                {JOptionPane.showMessageDialog(rootPane, "Incorrect UserName or Password", "Failed", 1);
                }
                
                } 
        catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "Empty Values detected", "Failed", 1);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Incorrect Values", "Failed", 1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jUsername;
    private javax.swing.JTextField jpassword;
    // End of variables declaration//GEN-END:variables
}
